import { createApp } from 'vue';
import App from './App.vue';
import router from './router';
import ElementPlus from 'element-plus';
import 'element-plus/dist/index.css';
import { store, key } from './store';
import './utils/axios.config';
const app = createApp(App);
app.use(router);
app.use(ElementPlus);
app.use(store, key);
app.mount('#app');
